# num_inferences: 100
# num_threads: 16
# model_cfg: model/alexnet.cfg
# model_weight: model/alexnet.weights
# data_dir: data


num_inferences: 100
num_threads: 8
model_cfg: model/resnet152.cfg
model_weight: model/resnet152.weights
data_dir: data
